### ISSUE TITLE
Screen damage

### ISSUE THREAD

**Issue by roflmaostc** [Dicklesworthstone/anti_alzheimers_flasher#1]
Hi,

just to raise awareness but this page literally damaged my monitor ( Dell Monitor – P2722H. A common LED LCD). Copied from [HackerNews](https://news.ycombinator.com/item?id=39142290).

I was running it three or four times, not longer than 10s each.

```
I'm not sure what just happened but this webpage literally damaged my monitor.

There is now some flickering over the whole screen (it's not my mind, I filmed and checked my mind with another screen) )

```

Slow Mo video of the flickering:  https://anonymfile.com/n7yX/vid-20240126151605.mp4

**Comment by adv0r** [comment]
Warning: This just fucked my 2k$ 4k LG display. I ran the website 15 minutes ago and quickly closed it after 15 seconds. My screen is still flickering 30 minutes later in the portion of the screen where it used to be the webpage. I rebooted.  Still happening.



FML please put a big disclaimer.

**Comment by roflmaostc** [comment]
It seems to slowly fade out even though I still notice it with indirect vision.

**Comment by Dicklesworthstone** [comment]
I responded to you on HN, but I will here as well. Very sorry about this, I tested it on 3 of my screens and it worked fine with no issues. I added a big disclaimer about it on the page so hopefully no one else will be impacted by this. Also, for what it's worth, several people said that the issue goes away after turning your screen off for 10 minutes.

**Comment by roflmaostc** [comment]
Yeah I can confirm it slowly fades out. Still slightly scary :laughing:

**Comment by Dicklesworthstone** [comment]
Also, apparently playing this video full screen for a while helps reset the screen:

https://youtu.be/t6jlhqNxRYk?si=O9uZli58WwjqNYnx

**Comment by roflmaostc** [comment]
Seems like my screen needs homeopathic therapy lol?

**Comment by adv0r** [comment]
it went away thankfully,

**Comment by Adachi91** [comment]
LG Ultra gear (27GN850-B), no issue for this monitor.

**Comment by r-mathieu** [comment]
After several minutes, my screen was still flickering and I saw a solution to restart the graphics driver with a shortcut (**_Ctrl+Shift+Win+B_**) and I think that totally solved my problem. If someone can confirm it too.

EDIT : Well, I tried again and it doesn't solve it

**Comment by Dicklesworthstone** [comment]
> After several minutes, my screen was still flickering and I saw a solution to restart the graphics driver with a shortcut (**_Ctrl+Shift+Win+B_**) and I think that totally solved my problem. If someone can confirm it too.
> 
> EDIT : Well, I tried again and it doesn't solve it

Try playing that video I linked to above and let it play for 10 minutes full screen. Then try turning off for a few minutes.
